### PR TITLE
Support an onJoin event

### PR DESCRIPTION
**Pull request by beaugunderson**
And update package.json to remove the warning for running on 0.10.x.

### CODE REVIEW

**Comment by leolara** [comment]
@beaugunderson why is presences a global variable instead of instance variable?

**Comment by beaugunderson** [comment]
@leolara Ha, yes, makes much more sense as an instance variable. :)

**Comment by beaugunderson** [comment]
@leolara Updated the pull request to make `presences` an instance variable.

**Comment by leolara** [comment]
@beaugunderson the constructor is the method that starts at line 210, you need to initalise it on that method for being an instance field. Still I do not understand the rest of the code. What is variable x for?

**Comment by beaugunderson** [comment]
@leolara Fixed (again), sorry. :)

Re: the `x` element, it's extended presence information and contains the `item` element, which has the `role` attribute. In my testing we only want to handle joins from roles of type 'participant' or 'visitor'.

More information here: http://xmpp.org/extensions/xep-0045.html#enter-pres

Also fixed the variable scope issues in this version (body, x, fromJid, fromNick, and fromChannel were all being redefined).

**Comment by aaronpk** [comment]
This looks super useful, and I was about to start writing this myself. Any reason this hasn't been merged in yet?

**Pull request closed without merging**
